version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout
      - run: mkdir -p $HOME/.docker/ && ( echo $DOCKER_CFG | base64 -d > $HOME/.docker/config.json )
      - setup_remote_docker
      - run: sh build.sh
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build